### ISSUE TITLE
Port "addSolution" to atk core Exceptions and UI 

### ISSUE THREAD

**Issue by romaninsh** [atk4/core#108]
be considerate of #93 ..

https://github.com/atk4/atk4/blob/4.4/lib/BaseException.php#L137

**Comment by abbadon1334** [comment]
I think this can be really interesting

**Comment by pkly** [comment]
Somewhat related: I was thinking about allowing a few other things to be added/changed in the exceptions.
Name being one of them, since now it will always say "Agile Toolkit Exception".
It'd be rather easy to change that to pull the name from a variable (protected) and that'd allow you to create new exceptions that inherit from atk4/core and override that name for better user experience.

It'd also be nice to add some sort of data that can be stored with the exception - currently you can only add the params, which is not ideal - it'd be better if you'd allow data that doesn't need keys, simply the value and then display it to the end-user.

**Comment by pkly** [comment]
Fixed by #109 so this should be closed.
@romaninsh
